# Generated by Django 5.0.6 on 2025-10-12 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=255)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['step__step_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('trigger_source', models.CharField(choices=[('manual', 'Manual Trigger'), ('webhook', 'Webhook'), ('schedule', 'Scheduled'), ('retry', 'Retry')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(max_length=50)),
                ('step_order', models.IntegerField()),
                ('config', models.JSONField(default=dict)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('condition', models.JSONField(default=dict, help_text='JSON condition for when this step should run')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='workflow_json',
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='successful_executions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflow',
            name='total_executions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflow',
            name='trigger_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workflow',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('webhook', 'Webhook'), ('schedule', 'Schedule')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['created_by', 'is_active'], name='workflows_w_created_2024f8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['created_at'], name='workflows_w_created_705cd8_idx'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='parent_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='workflows.workflowexecution'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='workflow_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='workflows.workflowexecution'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='failed_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_executions', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflowstep'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['workflow', 'step_order'], name='workflows_w_workflo_8d40e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_f6053d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'started_at'], name='workflows_w_status_9f5713_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['created_at'], name='workflows_w_created_cdee1f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['workflow_execution', 'status'], name='workflows_t_workflo_597835_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status', 'next_retry_at'], name='workflows_t_status_4bab62_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['step', 'status'], name='workflows_t_step_id_545039_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['created_at'], name='workflows_t_created_fd3137_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskexecution',
            unique_together={('workflow_execution', 'step')},
        ),
    ]
