# Generated by Django 5.0.6 on 2025-10-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_taskexecution_workflowexecution_workflowstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflows.workflow'),
        ),
    ]
