# Generated by Django 5.0.6 on 2026-03-14 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflowexecution_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecution',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='error_traceback',
        ),
        migrations.CreateModel(
            name='TaskExeErrorTraceback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('task_exe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_tracebacks', to='workflows.taskexecution')),
            ],
        ),
    ]
